FROM nginx:alpine

ARG GIT_SHA="unknown"

RUN mkdir -p /tmp/fulltech

COPY deploy_web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i "s/__FULLTECH_BUILD_VERSION__/${GIT_SHA}/g" /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
