FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app

ARG API_BASE_URL
ARG STORAGE_PUBLIC_URL
ARG FLUTTER_BUILD_ARGS=""
ARG GIT_SHA="unknown"

COPY frondend/pubspec.* ./
RUN flutter pub get

COPY frondend/ ./

RUN if [ -n "$API_BASE_URL" ]; then \
      flutter build web --release --dart-define=API_BASE_URL="$API_BASE_URL" --dart-define=STORAGE_PUBLIC_URL="$STORAGE_PUBLIC_URL" $FLUTTER_BUILD_ARGS; \
    else \
      flutter build web --release --dart-define=STORAGE_PUBLIC_URL="$STORAGE_PUBLIC_URL" $FLUTTER_BUILD_ARGS; \
    fi

FROM nginx:alpine

COPY --from=build /app/build/web /usr/share/nginx/html
COPY frondend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
