-- Add intelligent product fields to catalogo table
ALTER TABLE "catalogo"
  ADD COLUMN IF NOT EXISTS "tipo_producto" TEXT NOT NULL DEFAULT 'producto',
  ADD COLUMN IF NOT EXISTS "incluye" TEXT,
  ADD COLUMN IF NOT EXISTS "permite_adicionales" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "es_cotizable" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "orden" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cantidad_base" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "unidad_adicional_nombre" TEXT,
  ADD COLUMN IF NOT EXISTS "precio_adicional" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "precio_minimo_adicional" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "permite_calculo_adicional" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "ciudad_base" TEXT NOT NULL DEFAULT 'Higüey',
  ADD COLUMN IF NOT EXISTS "cargo_fuera_ciudad" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "aplica_cargo_fuera_ciudad" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "instalacion_incluida" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "reglas_calculo" JSONB NOT NULL DEFAULT '{}';
